version: '3.8'

services:
  python_backend:
    build:
      context: .
    ports:
      - "8001:8001"
    networks:
      - backend_network
    volumes:
      - ./:/app:delegated
      - /app/.venv
    environment:
      - ENV=development
    env_file:
      - ../.env

networks:
  backend_network:
    driver: bridge